#+TITLE: Getting Started with Create React App

* Scripts
** ~npx create-react-app demo-app~
   Creates a react app.
** ~cd demo-app~
   Moves to the react app folder.
** ~npm start~
   Runs the app in the development mode. Open [[http://localhost:3000]] to
   view it in the browser.

** ~npm test~
   Launches the test runner in the interactive watch mode. See the
   section about [[https://facebook.github.io/create-react-app/docs/running-tests][running tests]] for more information.

** ~npm run build~
   Builds the app for production to the `build` folder. It correctly
   bundles React in production mode and optimizes the build for the
   best performance. The build is minified and the filenames include
   the hashes. Your app is ready to be deployed! See the section about
   [[https://facebook.github.io/create-react-app/docs/deployment][deployment]] for more information.

** ~npm run eject~
   *Note: this is a one-way operation. Once you `eject`, you can’t go back!*
   If you aren’t satisfied with the build tool and configuration
   choices, you can `eject` at any time. This command will remove the
   single build dependency from your project. Instead, it will copy
   all the configuration files and the transitive dependencies
   (webpack, Babel, ESLint, etc) right into your project so you have
   full control over them. All of the commands except `eject` will
   still work, but they will point to the copied scripts so you can
   tweak them. At this point you’re on your own. You don’t have to
   ever use `eject`. The curated feature set is suitable for small and
   middle deployments, and you should not feel obligated to use this
   feature. However we understand that this tool would not be useful if
   you could not customize it when you are ready for it.

* Learn More
  - [[https://facebook.github.io/create-react-app/docs/getting-started][Create React App documentation]].
  - [[https://reactjs.org/][React documentation]].
  - [[https://facebook.github.io/create-react-app/docs/code-splitting][Code Splitting]].
  - [[https://facebook.github.io/create-react-app/docs/analyzing-the-bundle-size][Analyzing the Bundle Size]].
  - [[https://facebook.github.io/create-react-app/docs/making-a-progressive-web-app][Making a Progressive Web App]].
  - [[https://facebook.github.io/create-react-app/docs/advanced-configuration][Advanced Configuration]]
  - [[https://facebook.github.io/create-react-app/docs/deployment][Deployment]]
  - [[https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify][npm run build fails to minify]]

* Six Main Concepts
** ~Jsx~
   - replace ~class~ with ~className~
   - for dynamic content no ~$~ sign is needed, only ~{}~.
   - we can declare style object and set is as style value
     #+BEGIN_EXAMPLE
       const styleObject = {
	 color: 'white',
	 backgroundColor: 'black'
       }

       return(
	 <div className="App">
	   <p style={styleObject}>My Name is Khan</p>
	 </div>
       )
     #+END_EXAMPLE
** Component

** Props

** Event

** State

** Load Data
